spring:
  application:
    name: eureka-service
server:            
  port: 8761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:        
    peer-node-read-timeout-ms: 300000
    enable-self-preservation: false